# Form implementation generated from reading ui file 'addmodelwizard.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import json

def run_from_mainapp():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 300)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(parent=Form)
        self.okButton.setGeometry(QtCore.QRect(310, 270, 56, 17))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(parent=Form)
        self.cancelButton.setGeometry(QtCore.QRect(380, 270, 56, 17))
        self.cancelButton.setObjectName("cancelButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 80, 211, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setGeometry(QtCore.QRect(220, 80, 56, 17))
        self.addButton.setObjectName("addButton")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 251, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.cancelButton.clicked.connect(Form.close) # type: ignore
        self.okButton.clicked.connect(Form.close) # type: ignore
        self.addButton.clicked.connect(self.add_model)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add_model(self):
        model = self.lineEdit.text()
        config = {
            "settings": {
                "model": model
            }
        }
        out_file = open("ollama_settings.json", "w")
        json.dump(config, out_file)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Welcome to Add Model Wizard"))
        self.okButton.setText(_translate("Form", "OK"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.addButton.setText(_translate("Form", "Add"))
        self.label_2.setText(_translate("Form", "Enter the model you want to add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
